### ISSUE TITLE
Check presence of cuda-compatible devices in GPU grid workers

### ISSUE THREAD

**Issue by tkornut** [IBM/mi-prometheus#18]
Currently, they just crash and output:

Traceback (most recent call last):
  File "/home/tkornuta/anaconda3/bin/mip-gridtester-gpu", line 11, in <module>
    load_entry_point('miprometheus==0.2.0', 'console_scripts', 'mip-gridtester-gpu')()
  File "/home/tkornuta/pytorch-env/mi-prometheus/miprometheus/workers/grid_tester_gpu.py", line 118, in main
    grid_tester_gpu.run_grid_experiment()
  File "/home/tkornuta/pytorch-env/mi-prometheus/miprometheus/workers/grid_tester_gpu.py", line 87, in run_grid_experiment
    with ThreadPool(processes=torch.cuda.device_count()) as pool:
  File "/home/tkornuta/anaconda3/lib/python3.6/multiprocessing/pool.py", line 789, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/home/tkornuta/anaconda3/lib/python3.6/multiprocessing/pool.py", line 167, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

**Comment by vmarois** [comment]
Adressed in #23
